name: Build on macOS
on: push

jobs:
  build:
    runs-on: macos-12
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install build deps
        run: brew install nim scons yasm
      - name: Install nim
        run: |
          curl -LO https://github.com/nim-lang/nightlies/releases/download/2023-06-27-version-1-6-71ba2e7f3c5815d956b1ae0341b0743242b8fec6/nim-1.6.14-macosx_x64.tar.xz
          tar xzf nim-1.6.14-macosx_x64.tar.xz
          echo "$(pwd)/nim-1.6.14/bin" >> $GITHUB_PATH
      - name: Update path
        run: echo "$HOME/.nimble/bin" >> $GITHUB_PATH
      - name: Install Nimble 0.14.2
        run: nimble install -y nimble@0.14.2
      - name: Install nimble deps
        run: nimble setup
      - name: Save SHAs of submodules
        run: 'git submodule status > .submodules.tmp'
      - name: Prep dist config
        run: cp dist_config.example.json dist_config.json
      - name: prereq cache
        id: prereq-cache
        uses: actions/cache@v3
        with:
          path: |
            vendor/godot/bin
            fonts
          key: ${{ runner.os }}-prereq-cache-v2-${{ hashFiles('.submodules.tmp') }}
      - name: build prereqs
        run: nimble dist_prereqs
        if: steps.prereq-cache.outputs.cache-hit != 'true'
      - name: Dist
        run: nimble dist_package
      - uses: actions/upload-artifact@v3
        with:
          name: Enu macOS Distribution
          path: dist/*.dmg
